config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :plants
      resources :job_applications
      resources :rooms
      resources :vehicles
      resources :messages
      resources :materials

      root to: "users#index"
    end
   get 'rooms/index'
  resources :messages
  devise_for :users
  resources :vehicles do
    get :applications
    collection do
      get :my_vehicles
    end
    resources :job_applications do
      member do
        put :interviewed
        put :shortlisted
        put :hired
        put :rejected
      end
      collection do
        patch :approve
      end
    end
  end
  resources :plants do
    resources :materials
  end
  resources :messages, only: [:new, :create]
  resources :rooms
  root 'home#index'
  get 'home/about'
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
################################ Relationships ########################

  belongs_to :user
  belongs_to :vehicle
  has_one_attached :cv
  has_rich_text :content

  include AASM
  aasm timestamps: true do
    state :new, initial: true
    state :interviewed
    state :shortlisted
    state :hired
    state :rejected

    event :interviewed do
      transitions from: :new, to: :interviewed
    end
    event :shortlisted do
      transitions from: :interviewed, to: :shortlisted
    end
    event :hired do
      transitions from: :shortlisted, to: :hired
    end
    event :rejected do
      transitions from: [:new, :interviewed, :shortlisted], to: :rejected
    end

  end


  ########################## VOlidation  ##########################
  validates :cv, attached: true, content_type: [:pdf]
end

app/controllers/admin/job_applications_controller.rb
module Admin
  class JobApplicationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_jobapplication, only: %i[  edit update destroy ]

  def index
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_applications = JobApplication.all
  end

  def show
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.find(params[:id])
    @user = @job_application.user
  end

  def interviewed
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.find(params[:id])
    if @job_application.interviewed!
      redirect_to vehicle_job_applications_url, notice: "Candidate has been  Successfuly Called for Interview." 
    else
      redirect_to vehicle_job_applications_url, notice: "some thing has went wrong try again"
    end
  end

  def shortlisted
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.find(params[:id])
    if @job_application.shortlisted!
      redirect_to vehicle_job_applications_url, notice: "Candidate has been Shortlisted."
    else
      redirect_to vehicle_job_applications_url, notice: "some thing has went wrong try again"
    end
  end

  def hired
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.find(params[:id])
    if @job_application.hired!
      redirect_to vehicle_job_applications_url, notice: "Candidate hasbeen Successfuly Hired."
    else
      redirect_to vehicle_job_applications_url, notice: "some thing has went wrong try again"
    end
  end

  def rejected
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.find(params[:id])
    if @job_application.rejected!
      redirect_to vehicle_job_applications_url, notice: "Candidate has been Rejected Successfuly."
    else
      redirect_to vehicle_job_applications_url, notice: "some thing has went wrong try again"
    end
  end

  def approve
    @job_application = JobApplication.find(params[:job_application_id])
    @user = @job_application.user 
    if current_user.id == @user.id  
    else
      if @user.user_type == "first_driver"
        @apprive_first = @job_application.vehicle.update(first_driver:@job_application.user)
        redirect_to vehicle_job_applications_url, notice: "Candidate hasbeen Successfuly Hired."
       
      else
        @apprive_second = @job_application.vehicle.update(second_driver:@job_application.user)
        redirect_to vehicle_job_applications_url, notice: "Candidate hasbeen Successfuly Hired."
      end
    end
  end

  def new
    @job_application = Job_application.new
    @job_application.user_id = current_user
    @user_id = current_user.id
  end

  def edit
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.new(job_application_params)
    @user_id = current_user.id
    @email = current_user.email
    @name = current_user.first_name
    @job_application.user_id = current_user.id
    @job_application.user = current_user
    @vehicle = Vehicle.find(params[:vehicle_id])
    @job_application = @vehicle.job_applications.create(job_application_params)
    @job_application.user_id = current_user.id
    respond_to do |format|
      if @job_application.save
        format.html { redirect_to vehicle_job_applications_url, notice: "Job_application was successfully created." }
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to @job_application, notice: "Job_application was successfully updated." }
        format.json { render :show, status: :ok, location: @job_application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job_application.destroy
    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: "Job_application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_job_application
      @vehicle = Vehicle.find(params[:vehicle_id])
      @job_application = @vehicle.job_application.find(params[:id])
    end

    def job_application_params
      params.require(:job_application).permit(:name, :email, :description, :user_id, :vehicle_id, :cv, :content )
    end
end

app/helpers/jobapplications_helper.rb
module JobapplicationsHelper
end

app/views/job_applications/_form.html.erb
<%= form_with(model: jobapplication) do |form| %>
  <% if jobapplication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jobapplication.errors.count, "error") %> prohibited this jobapplication from being saved:</h2>

      <ul>
        <% jobapplication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <%= form.file_field :cv, class:'form-label form-control', placeholder: 'cv'%>
  <div class="actions">
    <%= form.submit %>
  </div>
                

<% end %>

app/views/job_applications/edit.html.erb
<h1>Editing Job_application</h1>

<%= render 'form', job_application: @job_application %>

<%= link_to 'Show', @job_application %> |
<%= link_to 'Back', job_applications_path %>

app/views/job_applications/index.html.erb
<br><br>
			<h3 class="text-center"> Application </h3>
<div class="m-4">
	<ul class="nav nav-tabs" id="myTab">
		<li class="nav-item">
			<a href="#home" class="nav-link active" data-bs-toggle="tab">Applications for First Driver</a>
		</li>
		<li class="nav-item">
			<a href="#profile" class="nav-link" data-bs-toggle="tab">Applications for Second Driver</a>
		</li>
	</ul>
	<div class="tab-content bg-white">
		<div class="tab-pane fade show active" id="home">
			<% if  @vehicle.job_applications.present?  %>
				<div class="container px-5 py-5">
					<div class="row">
						<div class="col mx-1 border-end border-start ">
							<p class="fs-6 fw-bold text-center"> New </p>
							<% @vehicle.job_applications.each do |job_application| %>
								<% if User.find(job_application.user_id).user_type == User::USER_TYPE_FIRST_DRIVER %>
									<% if job_application.aasm_state == "new" %>
										<div class="card border border-2" style="width: 10rem;">
											<% if User.find(job_application.user_id).avatar.attached? %>
												<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
											<% end %>
											<div class="card-body text-center">
												<h5 class="card-title text-center"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
												<% if current_user.id == job_application.user_id %>
												<% else %>
													<button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Call for Interview">
														<%= link_to "Interview", interviewed_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-light' %>
													</button>`
													<br>
													 <p class="text-center"><small>OR<br></small>
													<%= link_to " Reject", rejected_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-danger text-center' %>
												<% end %>
											</div>
										</div><br>
									<% end %>
								<% end %>
							<% end %>
						</div>
						<div class="col mx-1 border-end  ">
							<p class="fs-6 fw-bold text-center"> Interviewed </p>
							<% @vehicle.job_applications.each do |job_application| %>
								<% if User.find(job_application.user_id).user_type == User::USER_TYPE_FIRST_DRIVER %>
									<% if job_application.aasm_state == "interviewed" %>
										<div class="card border border-2" style="width: 10rem;">
											<% if User.find(job_application.user_id).avatar.attached? %>
												<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
											<% end %>
											<div class="card-body text-center">
												<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
												<% if current_user.id == job_application.user_id %>
												<% else %>
												<button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Add to shortlist">
													<%= link_to "Shortlist", shortlisted_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-light' %>
												</button>
													<br>
													<p class="fw-lighter text-center"> OR <br>
													<%= link_to " Reject", rejected_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-danger' %>
												<% end %>
											</div>
										</div><br>
									<% end %>
								<% end %>
							<% end %>
							<br>
						</div>
						<div class="col mx-1 border-end">
							<p class="fs-6 fw-bold text-center"> Shortlisted </p>
							<% @vehicle.job_applications.each do |job_application| %>
								<% if User.find(job_application.user_id).user_type == User::USER_TYPE_FIRST_DRIVER %>
									<% if job_application.aasm_state == "shortlisted" %>
										<div class="card border border-2" style="width: 10rem;">
											<% if User.find(job_application.user_id).avatar.attached? %>
												<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
											<% end %>
											<div class="card-body text-center">
												<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
												<% if current_user.id == job_application.user_id %>
												<% else %>
													<button type="button" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Click to Hire">
														<%= link_to "Hire", hired_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-light' %>
													</button>
													<br>
													 <p class="text-center">OR<br>
													<%= link_to " Reject", rejected_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-danger text-center' %>
												<% end %>
											</div>
										</div><br>
									<% end %>
								<% end %>
							<% end %>
						</div>
						<div class="col mx-1 border-end">
							<p class="fs-6 fw-bold text-center"> Hired  </p>
							<% @vehicle.job_applications.each do |job_application| %>
								<% if User.find(job_application.user_id).user_type == User::USER_TYPE_FIRST_DRIVER %>
									<% if job_application.aasm_state == "hired" %>
										<div class="card border border-2 " style="width: 10rem;">
											<% if User.find(job_application.user_id).avatar.attached? %>
												<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
											<% end %>
											<div class="card-body text-center">
												<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
											</div>
										</div><br>
									<% end %>
								<% end %>
							<% end %>
						</div>
						<div class="col mx-1 border-end">
							<p class="fs-6 fw-bold text-center"> Rejected  </p>
							<% @vehicle.job_applications.each do |job_application| %>
								<% if User.find(job_application.user_id).user_type == User::USER_TYPE_FIRST_DRIVER %>
									<% if job_application.aasm_state == "rejected" %>
										<div class="card border border-2" style="width: 10rem;">
											<% if User.find(job_application.user_id).avatar.attached? %>
												<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
											<% end %>
											<div class="card-body text-center">
												<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
											</div>
										</div><br>
									<% end %>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
			<br>
		</div>
		<div class="tab-pane fade" id="profile">
			<% if  @vehicle.job_applications.present?  %>
				<div class="container px-5 py-5">
					<div class="container">
						<div class="row">
							<div class="col mx-1 border-end">
									<p class="fs-6 fw-bold text-center"> New  </p>
								<% @vehicle.job_applications.each do |job_application| %>
									<% if User.find(job_application.user_id).user_type == User::USER_TYPE_SECOND_DRIVER %>
										<% if job_application.aasm_state == "new" %>
											<div class="card border border-2 " style="width: 10rem;">
												<% if User.find(job_application.user_id).avatar.attached? %>
													<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
												<% end %>
												<div class="card-body text-center">
													<h5 class="card-title"><<%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
													<% if current_user.id == job_application.user_id %>
													<% else %>
														<%= link_to "Interview", interviewed_vehicle_job_application_path(id: job_application.id ), method: :put, class:'btn btn-secondary btn-sm' %><br>
														<p class="text-center fs-6"> OR</p>
														<%= link_to " Reject", rejected_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-danger' %>
													<% end %>
												</div>
											</div><br>
										<% end %>	
									<% end %>
								<% end %>
								</div>
								<div class="col mx-1 border-end">
								<p class="fs-6 fw-bold text-center"> Interviewed  </p>
								<% @vehicle.job_applications.each do |job_application| %>
									<% if User.find(job_application.user_id).user_type == User::USER_TYPE_SECOND_DRIVER %>
										<% if job_application.aasm_state == "interviewed" %>
											<div class="card border border-2 " style="width: 10rem;">
												<% if User.find(job_application.user_id).avatar.attached? %>
													<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
												<% end %>
												<div class="card-body text-center">
													<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
													<% if current_user.id == job_application.user_id %>
													<% else %>
														<%= link_to "Shortlist", shortlisted_vehicle_job_application_path(id: job_application.id ), method: :put, class:'btn btn-secondary btn-sm' %><br>
														<p class="fw-lighter text-center"> OR</p>
														<%= link_to " Reject", rejected_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-danger'%>
													<% end %>
												</div>
											</div><br>
										<% end %>
									<% end %>
								<% end %>
								</div>
								<div class="col mx-1 border-end">
									<p class="fs-6 fw-bold text-center"> Shortlisted  </p>
									<% @vehicle.job_applications.each do |job_application| %>
										<% if User.find(job_application.user_id).user_type == User::USER_TYPE_SECOND_DRIVER %>
											<% if job_application.aasm_state == "shortlisted" %>
												<div class="card border border-2 " style="width: 10rem;">
													<% if User.find(job_application.user_id).avatar.attached? %>
														<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
													<% end %>
													<div class="card-body text-center">
														<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
														<% if current_user.id == job_application.user_id %>
														<% else %>
															<button type="button" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Click to Hire">
																<%= link_to "Hire", hired_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-light' %>
															</button>
															<br>
													 <p class="text-center fs-6">OR<br>
														<%= link_to " Reject", rejected_vehicle_job_application_path(id: job_application.id ), method: :put, class:'text-danger text-center' %>
															
														<% end %>
													</div>
												</div><br>
											<% end %>
										<% end %>
									<% end %>
								</div>
								<div class="col mx-1 border-end">
									<p class="fs-6 fw-bold text-center"> Hired </p>
									<% @vehicle.job_applications.each do |job_application| %>
										<% if User.find(job_application.user_id).user_type == User::USER_TYPE_SECOND_DRIVER %>
											<% if job_application.aasm_state == "hired" %>
												<div class="card border border-2 " style="width: 10rem;">
													<% if User.find(job_application.user_id).avatar.attached? %>
														<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
													<% end %>
													<div class="card-body text-center">
														<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
													</div>
												</div><br>
											<% end %>
										<% end %>
									<% end %>
								</div>
								<div class="col mx-1 border-end">
									<p class="fs-6 fw-bold text-center"> Rejected </p>
									<% @vehicle.job_applications.each do |job_application| %>
										<% if User.find(job_application.user_id).user_type == User::USER_TYPE_SECOND_DRIVER %>
											<% if job_application.aasm_state == "rejected" %>
												<div class="card border border-2 " style="width: 10rem;">
													<% if User.find(job_application.user_id).avatar.attached? %>
														<%= image_tag User.find(job_application.user_id).avatar, class:'card-img-top'%>
													<% end %>
													<div class="card-body text-center">
														<h5 class="card-title"><%= link_to User.find(job_application.user_id).first_name+User.find(job_application.user_id).last_name, vehicle_job_application_path(id: job_application.id) %></h5>
													</div>
												</div><br>
											<% end %>
										<% end %>
									<% end %>
								</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/job_applications/new.html.erb
<h1>New Job_application</h1>

<%= render 'form', job_application: @job_application %>

<%= link_to 'Back', job_applications_path %>

app/views/job_applications/show.html.erb
<div class="contailner">
  <div class="row">
    <div class="col-7" >
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label "><strong> Cover Letter</strong></label><br>
        <%= @job_application.description %>
        <%= @job_application.content %>
      </div>
    </div>
    <div class="col">
      <% if current_user.id == @user.id %>
      <%else%>
        <% if @job_application.aasm_state == 'hired'  %>
          <%= link_to 'approve', approve_vehicle_job_applications_path(job_application_id: @job_application.id), :method=> :patch, class: 'fas btn btn-outline-success ' %>
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, class:'card-img-top'%>
      <% end %>
      <p> 
        <strong> User Name: </strong>
        <%= @user.first_name+@user.last_name %>
      </p>
      <p>
        <strong>Email: </strong>
        <%= @user.email%> 
      </p>
      <p> 
        <strong>Licence Number: </strong> 
        <%= @user.licence_number %>
      </p>
      <p>
        <strong>Birthday: </strong>
        <%= @user.birthday %>
      </p>
      
      <% if @user.address.present?%>
        <p> 
          <strong> Address: </strong>
          <%= @user.address %>
        </p>
      <% end %>
    </div>
  </div>
</div>