config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :plants
      resources :job_applications
      resources :rooms
      resources :vehicles
      resources :messages
      resources :materials

      root to: "users#index"
    end
   get 'rooms/index'
  resources :messages
  devise_for :users
  resources :vehicles do
    get :applications
    collection do
      get :my_vehicles
    end
    resources :job_applications do
      member do
        put :interviewed
        put :shortlisted
        put :hired
        put :rejected
      end
      collection do
        patch :approve
      end
    end
  end
  resources :plants do
    resources :materials
  end
  resources :messages, only: [:new, :create]
  resources :rooms
  root 'home#index'
  get 'home/about'
end

app/models/plant.rb
class Plant < ApplicationRecord
  ################################ Relationships ########################
    has_one_attached :avatar
    has_many :materials

  ################################ Validations ########################
    validates :avatar, attached: true, content_type: [:png, :jpg, :jpeg]
    
end

app/controllers/admin/plants_controller.rb
module Admin
  class PlantsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plant, only: %i[ show edit update destroy ]

  
  def index
    @plants = Plant.all
  end

  def show
  end

  def new
    @plant = Plant.new
  end

  def edit
  end

  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_plant
      @plant = Plant.find(params[:id])
    end

    def plant_params
      params.require(:plant).permit(:name, :address, :avatar)
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<div class="container-sm p-md-5 plant_form ">
      <div class= "container-sm">
          <%= form_with(model: plant) do |form| %>
            <% if plant.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

                <ul>
                  <% plant.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <form>
              <div>
                <%= form.text_field :name, class:'form-label form-control', placeholder: 'Name' %>
                <%= form.text_area :address, class:'form-label form-control', placeholder: 'Address' %>
                <%= form.file_field :avatar,class:'form-label form-control' %>
                <div class="actions text-start">
                  <%= link_to 'Back', @plant %>
                  <%= form.submit class: 'btn  btn btn-outline-primary text-end' %>
                </div>
               </div>
            </form>

            <% end %>
      </div>
</div>

app/views/plants/edit.html.erb
<div class="row_plant">
  <div class = "container-sm p-md-5 editing-vehicle col-8 ">
      <h2 class = 'text-center p-4'>Editing Plant</h2>
      <%= render 'form', plant: @plant %>
  </div>
</div>

app/views/plants/index.html.erb
<div class = "container p-5">
  <h1 class= "text-center p-md-4">Plants </h1>
  <p class="text-end"><%= link_to 'New Plant', new_plant_path, class: 'btn btn-secondary'  %></p>
  <div class = "row row-cols-1 row-cols-md-3 g-4">
    <% @plants.each do |plant| %>
    <div class="col">
      <div class="card h-100">
        <div >
          <% if plant.avatar.attached? %>
          <%= image_tag plant.avatar, class:'card-img-top image_style'%>
          <% else %>
          <% end %>
        </div>
        <div class="card-body ">
          <h5 class="card-title"><%= link_to plant.name, plant %></td>
          <h5><%= plant.address %></h5>
        </div>
      </div>
    </div>
    <% end %>
  </div><br />
</div>

app/views/plants/new.html.erb
<div class = "container-sm  new-vehicle col-8">
	<h2 class = 'text-center p-4'>New Plant</h2>

	      <%= render 'form', plant: @plant %>
</div>

app/views/plants/show.html.erb
<div class="container-sm p-md-5 ">
  <div class="card mb-3 ">
    <div class="row">
        <div class="col-6">
          <div class="card-body">
            <table class="table">
              <tbody>
                <tr>
                  <th scope="row">Name:</th>
                  <td><%= @plant.name %></td>
                </tr>
                <tr>
                  <th scope="row">Address</th>
                  <td><%= @plant.address %></td>
                </tr>
              </tbody>
            </table>
            <%= link_to 'Back', plants_path, class: 'btn  btn btn-outline-dark ' %>
            <%= link_to 'Edit', edit_plant_path(@plant), class: 'fas btn btn-outline-info ' %>
            <%= link_to 'Delete', @plant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fas btn btn-outline-danger ' %>
          </div>
        </div>
        <div class="col">
          <% if @plant.avatar.attached? %>
          <%= image_tag @plant.avatar, class:'card-img-top image_style'%>
          <% end %>
        </div>
    </div>
  </div>
</div>
<div class = "container p-5">
  <h1 class= "text-center p-md-4">Materials</h1>
    <p class="text-end">    <%= link_to 'New Material', new_plant_material_path(plant_id: @plant.id), class: 'btn btn-secondary te'  %>
    </p>
    <div class = "row row-cols-1 row-cols-md-3 g-4">
      <% @plant.materials.each do |material| %>
      <div class="col">
        <div class="card h-100">
          <div >
            <% if material.avatar.attached? %>
              <%= image_tag material.avatar, class:'card-img-top image_style'%>
            <% else %>
            <% end %>
          </div>
          <div class="card-body ">
            <h5 class="card-title"><%= link_to material.name, plant_material_path(plant_id: material.plant.id, id: material.id)  %></h5>
            <h5><%= material.cost %></h5>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <br>
</div>

</br></br></br></br></br></br></br>