config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :plants
      resources :job_applications
      resources :rooms
      resources :vehicles
      resources :messages
      resources :materials

      root to: "users#index"
    end
   get 'rooms/index'
  resources :messages
  devise_for :users
  resources :vehicles do
    get :applications
    collection do
      get :my_vehicles
    end
    resources :job_applications do
      member do
        put :interviewed
        put :shortlisted
        put :hired
        put :rejected
      end
      collection do
        patch :approve
      end
    end
  end
  resources :plants do
    resources :materials
  end
  resources :messages, only: [:new, :create]
  resources :rooms
  root 'home#index'
  get 'home/about'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  ################################ Relationships ########################

	has_one_attached :avatar , dependent: :destroy
	has_many :materails , dependent: :destroy
	belongs_to :user
	has_many :job_applications , dependent: :destroy

	has_one :first_driver , class_name: "User", foreign_key: :first_driver_id
	has_one :second_driver, class_name: "User", foreign_key: :second_driver_id

  ################################ Valadations ########################
	validates :name, presence: true
	validates :color, presence: true
	validates :modle, presence: true
	validates :vehicle_number, presence: true
	validates :avatar, attached: true, content_type: [:png, :jpg, :jpeg]

end

app/controllers/admin/vehicles_controller.rb
module Admin
  class VehiclesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
	before_action :set_drivers, only: [:new, :edit, :update, :destroy, :create]

	def index
		@vehicles = Vehicle.all
	end
	
	def show
		@user_id = @vehicle.user_id
		@user = User.find(@vehicle.user_id)
		@job_application = @vehicle.job_applications

	end

	def new
		@vehicle = Vehicle.new
		
	end

	def my_vehicles
		@vehicles = Vehicle.all
	end

	def edit
    if @vehicle.user_id == current_user.id
    else
			redirect_to vehicles_path,class: 'alert alert-warning',notice: "Not Authorized to this vehicle"
		end

	end


	def create
		@vehicle = Vehicle.new(vehicle_params)
		@vehicle.user_id = current_user.id
		if params[:vehicle][:first_driver_id].present?
			@vehicle.first_driver = User.find(params[:vehicle][:first_driver_id])
		end
		if params[:vehicle][:second_driver_id].present?
			@vehicle.second_driver = User.find(params[:vehicle][:second_driver_id])
		end
		respond_to do |format|
			if @vehicle.save
				format.html { redirect_to @vehicle, notice: "Vehicle was successfully created." }
				format.json { render :show, status: :created, location: @vehicle }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @vehicle.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		if @vehicle.user_id == current_user.id
			if params[:vehicle][:first_driver_id].present?
				@vehicle.first_driver = User.find(params[:vehicle][:first_driver_id])
			end
			if params[:vehicle][:second_driver_id].present?
				@vehicle.second_driver = User.find(params[:vehicle][:second_driver_id])
			end
			respond_to do |format|
				if @vehicle.update(vehicle_params)
						format.html { redirect_to @vehicle, notice: "Vehicle was successfully updated." }
						format.json { render :show, status: :ok, location: @vehicle }
				else
						format.html { render :edit, status: :unprocessable_entity }
						format.json { render json: @vehicle.errors, status: :unprocessable_entity }
				end
			end
		else
			redirect_to vehicles_path, notice: "Not Authorized to this vehicle"
		end
	end

	def destroy
		if @vehicle.user_id == current_user.id
			@vehicle.destroy
			respond_to do |format|
				format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
				format.json { head :no_content }
			end
		else
			redirect_to vehicles_path, notice: "Not Authorized to this vehicle"
		end
	end

	def set_vehicle
		@vehicle = Vehicle.find(params[:id])
	end

	def set_drivers
		@first_driver_ids = User.where(user_type:  User::USER_TYPE_FIRST_DRIVER).pluck(:first_name, :id)
		@second_driver_ids = User.where(user_type: User::USER_TYPE_SECOND_DRIVER).pluck(:first_name, :id)
	end

	def vehicle_params
		params.require(:vehicle).permit(:name, :vehicle_number, :color, :modle, :avatar, :user_id, :my_vehicles )
	end
	
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<div class = "row_a">
  <div class="col-2">
  </div>
  <div>
    <div class= "container-sm vehicle ">
      <div class="text-center mt-4"></br></br>
        <%= form_with(model: vehicle) do |form| %>
          <% if vehicle.errors.any? %>
            <div class="row justify-content-md-center">
              <div id="error_explanation">
                <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
                <ul>
                  <% vehicle.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
          <div class="row justify-content-md-center">
            <div class="">
              <%= form.text_field :name, class:'form-label form-control', placeholder: 'Name'%>
              <%= form.text_field :color, class:'form-label form-control', placeholder: 'Color of Vehicle' %>
              <%= form.text_field :vehicle_number, class:'form-label form-control', placeholder: 'Vechile Number' %>
              <%= form.number_field :modle, class:'form-label form-control', placeholder: 'Vechile Modle'%>
              <%= form.file_field :avatar, class:'form-label form-control' %>
              <%= form.select :first_driver_id , @first_driver_ids, {include_blank: "First Drivers Name "}, {class:"form-select form-label"}%>
              <%= form.select :second_driver_id , @second_driver_ids, {include_blank: "Second Drivers Name"}, {class:"form-select form-label"}%>
              <div class="actions text-start">
              <%= link_to 'Back', @vehicle %>
                <%= form.submit class: 'btn  btn btn-outline-primary text-end' %><br /><br />
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/edit.html.erb
<div class = "container p-md-5 editing-vehicle ">
	<h2 class = 'text-center p-4'>Editing Vehicle</h2>
	<%= render 'form', vehicle: @vehicle %></br>
</div>

app/views/vehicles/index.html.erb
<div class = "container p-5">
  <h1 class= "text-center p-md-4">Vehicles  </h1>           
  <p class="text-end"><%= link_to 'Add New Vehicle', new_vehicle_path, class: 'btn btn-secondary' %></p>
  <div class = "row row-cols-1 row-cols-md-3 g-4">
    <% @vehicles.each do |vehicle| %>
      <div class="col">
        <div class="card h-100" >
          <div >
            <% if vehicle.avatar.attached? %>
              <%= image_tag vehicle.avatar, class:'card-img-top image_style'%> 
            <% else %>
            <% end %>
          </div>
          <div class="card-body ">
            <h5 class="card-title"><%=link_to vehicle.name, vehicle %>  </h5>
            <h5><%= vehicle.modle %> </h5>
          </div>
        </div>
      </div>
    <% end %>
  </div><br>
<div><br /> <br />

app/views/vehicles/my_vehicles.html.erb
<div class = "container p-5">
  <h1 class= "text-center p-md-4"> My Vehicles  </h1>
  <p class="text-end"><%= link_to 'Add New Vehicle', new_vehicle_path, class: 'btn btn-secondary' %></p>
  <div class = "row row-cols-1 row-cols-md-3 g-4">
    <% @vehicles.each do |vehicle| %>
      <% if vehicle.user_id == current_user.id%>
        <div class="col">
          <div class="card h-100">
            <div >
              <% if vehicle.avatar.attached? %>
                <%= image_tag vehicle.avatar, class:'card-img-top'%>
              <% else %>
              <% end %>
            </div>
            <div class="card-body ">
              <h5 class="card-title"><%=link_to vehicle.name, vehicle %>  </h5>
              <h5><%= vehicle.modle %> </h5>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div><br>
<div><br><br>

app/views/vehicles/new.html.erb
<div class = "container-sm p-md-5 col-6">
	<h2 class = 'text-center p-4'>New Vehicle</h2>
	<%= render 'form', vehicle: @vehicle %>
</div><br><br>

app/views/vehicles/show.html.erb
<div class="container p-md-5 ">
  <div class="card mb-3 ">
    <div class="row g-0">

      <div class="col-6 ">
        <div class="card-body">
          <table class="table ">
            <tbody>
              <tr>
                <th scope="row">Vehicle Name</th>
                <td><%= @vehicle.name %></td>
              </tr>
              <tr>
                <th scope="row">User Name</th>
                <td><%= @user.first_name %></td>
              </tr>
              <tr>
                <th scope="row">Driver Type</th>
                <td><%= @user.user_type %></td>
              </tr>
              <tr>
                <th scope="row">Vechile Number</th>
                <td><%= @vehicle.vehicle_number %></td>
              </tr>
              <tr>
                <th scope="row">Color</th>
                <td> <%= @vehicle.color %></td>
              </tr>
              <tr>
                <th scope="row">Modle</th>
                <td> <%= @vehicle.modle %> </td>
              </tr>
            </tbody>
          </table>
          <%= link_to 'Back', vehicles_path , class: 'btn  btn btn-outline-dark '  %>
          <% if @vehicle.user_id == current_user.id %>
            <%= link_to 'Edit', edit_vehicle_path, class: 'fas btn btn-outline-info ' %>
            <%= link_to 'Delete', @vehicle, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fas btn btn-outline-danger '  %>
            <%= link_to 'Applications', vehicle_job_applications_path(vehicle_id: @vehicle.id), class:'btn btn-outline-primary'  %>
          <% else %>
            <% if @vehicle.first_driver.present? %>
              <span class="d-inline-block" tabindex="0" data-mdb-toggle="tooltip" title="This Session is Already Filled.">
                <button class="btn btn-outline-success" style="pointer-events: none;" type="button" disabled>
                  Apply as a First Driver
                </button>
              </span>
            <% else %>
              <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Apply as a First Driver</button>
            <% end %>

            <% if @vehicle.second_driver.present? %>
              <span
                class="d-inline-block" tabindex="0" data-mdb-toggle="tooltip" title="This Session is Already Filled.">
                <button class="btn btn-outline-success" style="pointer-events: none;" type="button" disabled>
                  Apply as a Second Driver
                </button>
              </span>
            <% else %>
              <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal1" data-bs-whatever="@mdo">Apply as a Second Driver </button>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col mt-3 me-1">
        <% if @vehicle.avatar.attached? %>
          <%= image_tag @vehicle.avatar, class:'card-img-top'%>
        <% end %>
      </div>
  </div>
</div>
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Poppins" rel="stylesheet">
<section class="section-tours">
  <div class="row style-row">
    <% if @vehicle.first_driver.present? %>
      <div class="col-4">
        <div class="card card-style">
          <div class="card__side card__side--front">
          <div class="card__picture card__picture--1 card-img-top">  
              </div>
              <h4 class="card__heading">
                <span class="card__heading-span card__heading-span--1 fs-5">The First       Driver </span>
              </h4>
            <div class="card-up text-center">
              <% if @vehicle.first_driver.avatar.attached? %>
                <%= image_tag @vehicle.first_driver.avatar, class:'rounded-circle image-style'%>
              <% end %>  
            </div>

            <div class="card__details">
                <ul>
                    <li class="text-center"><%= @vehicle.first_driver.first_name %><%= @vehicle.first_driver.last_name %></li>
                </ul>
            </div>
          </div>
          <div class="card__side card__side--back card__side--back-1 ">
            <div class="card__cta">
              <div class="card__price-box">
                <ul>
                  <p class="fs-5"><%= @vehicle.first_driver.first_name %><%= @vehicle.first_driver.last_name %></p>
                  <p class="fs-5"><%= @vehicle.first_driver.address %></p>
                  <p class="fs-5"><%= @vehicle.first_driver.licence_number %></p>
                  <p class="fs-5"><%= @vehicle.first_driver.birthday %></p>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Apply  as a First Driver</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%if current_user.user_type == User::USER_TYPE_FIRST_DRIVER %>
                <%= form_with model: [ @vehicle, @vehicle.job_applications.build ] do |form| %>
                  <P>
                  <strong> Email: </strong>
                  <%= current_user.email%>
                  </p>
                  <p>
                  <strong>User Name:</strong>
                  <%= current_user.first_name+current_user.last_name %>
                  </p>
                  <%= form.label :content %>
                   <%= form.rich_text_area :content %>
                  <%= form.file_field :cv, class:'form-label form-control', placeholder: 'cv'%>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <div class="actions">
                <%= form.submit  'Apply', class:'btn btn-primary'%>
              </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if @vehicle.second_driver.present? %>
      <div class="col-4">
        <div class="card">
          <div class="card__side card__side--front">
            <div class="card__picture card__picture--2 card-img-top">  
            </div>
            <h4 class="card__heading">
              <span class="card__heading-span card__heading-span--2 fs-5">The Second Driver</span>
            </h4>
            <div class="card-up text-center">
              <% if @vehicle.second_driver.avatar.attached? %>
                <%= image_tag @vehicle.second_driver.avatar, class:'rounded-circle image-style'%>
              <% end %>  
            </div>
            <div class="card__details">
              <ul>
                <li class="text-center"><%= @vehicle.second_driver.first_name %><%= @vehicle.second_driver.last_name %></li>
              </ul>
            </div>
          </div>
          <div class="card__side card__side--back card__side--back-2">
            <div class="card__cta">
              <div class="card__price-box">
                <ul>
                  <p class="fs-5"><%= @vehicle.second_driver.first_name %><%= @vehicle.second_driver.last_name %></p>
                  <p class="fs-5"><%= @vehicle.second_driver.address %></P>
                  <p class="fs-5"><%= @vehicle.second_driver.licence_number %></P>
                  <p class="fs-5"><%= @vehicle.second_driver.birthday %></P>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Apply  as Second Driver</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= form_with model: [ @vehicle, @vehicle.job_applications.build ] do |form| %>
                <P>
                  <strong> Email: </strong> <%= current_user.email%>
                </p>
                <p>
                  <strong>User Name:</strong><%= current_user.first_name+current_user.last_name %>
                </p>
                <%= form.label :content %>
                <%= form.rich_text_area :content %>
                <%= form.file_field :cv, class:'form-label form-control', placeholder: 'Cv'%>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <div class="actions">
                  <%= form.submit 'apply', class:'btn btn-primary'%>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section><br/><br/>