config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :plants
      resources :job_applications
      resources :rooms
      resources :vehicles
      resources :messages
      resources :materials

      root to: "users#index"
    end
   get 'rooms/index'
  resources :messages
  devise_for :users
  resources :vehicles do
    get :applications
    collection do
      get :my_vehicles
    end
    resources :job_applications do
      member do
        put :interviewed
        put :shortlisted
        put :hired
        put :rejected
      end
      collection do
        patch :approve
      end
    end
  end
  resources :plants do
    resources :materials
  end
  resources :messages, only: [:new, :create]
  resources :rooms
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ActiveStorage::Attachment
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
################################ Relationships ########################

  belongs_to :user
  belongs_to :vehicle
  has_one_attached :cv
  has_rich_text :content

  include AASM
  aasm timestamps: true do
    state :new, initial: true
    state :interviewed
    state :shortlisted
    state :hired
    state :rejected

    event :interviewed do
      transitions from: :new, to: :interviewed
    end
    event :shortlisted do
      transitions from: :interviewed, to: :shortlisted
    end
    event :hired do
      transitions from: :shortlisted, to: :hired
    end
    event :rejected do
      transitions from: [:new, :interviewed, :shortlisted], to: :rejected
    end

  end


  ########################## VOlidation  ##########################
  validates :cv, attached: true, content_type: [:pdf]
end

app/models/material.rb
class Material < ApplicationRecord
  ################################ Relationships ########################
    has_one_attached :avatar, dependent: :destroy
    has_many :vehicles , dependent: :destroy
    belongs_to :plant

  ################################ Valadations ########################
    validates :avatar, attached: true, content_type: [:png, :jpg, :jpeg]
end

app/models/message.rb
class Message < ApplicationRecord
################################ Relationships ########################

	belongs_to :user
	belongs_to :room

################################ Volidation ########################

	validates :content, presence: true
	after_create_commit { MessageBroadcastJob.perform_later (self) }

end

app/models/plant.rb
class Plant < ApplicationRecord
  ################################ Relationships ########################
    has_one_attached :avatar
    has_many :materials

  ################################ Validations ########################
    validates :avatar, attached: true, content_type: [:png, :jpg, :jpeg]
    
end

app/models/room.rb
class Room < ApplicationRecord

################################ Relationships ########################
    has_many :messages , dependent: :destroy
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  ################################ Relationships ########################

  has_one_attached :avatar , dependent: :destroy
  has_many :job_applications , dependent: :destroy
  has_many :vehicles , dependent: :destroy
  belongs_to :first_vehicle, class_name:"Vehicle", foreign_key: :first_driver_id, optional: true
  belongs_to :second_vehicle, class_name:"Vehicle", foreign_key: :second_driver_id, optional: true
  
  has_one :second_driver, class_name: "User", foreign_key: "user_driver_id"
  belongs_to :first_driver, class_name: "User", optional: true

  has_many :messages , dependent: :destroy

    


  ########################## VOlidation  ##########################
  validates :avatar, attached: true, content_type: [:png, :jpg, :jpeg]



  ################################ Constants ############################


  USER_TYPE_FIRST_DRIVER = "first_driver"
  USER_TYPE_SECOND_DRIVER = "second_driver"
  USER_TYPES = [
    USER_TYPE_FIRST_DRIVER ,
    USER_TYPE_SECOND_DRIVER
  ]
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  ################################ Relationships ########################

	has_one_attached :avatar , dependent: :destroy
	has_many :materails , dependent: :destroy
	belongs_to :user
	has_many :job_applications , dependent: :destroy

	has_one :first_driver , class_name: "User", foreign_key: :first_driver_id
	has_one :second_driver, class_name: "User", foreign_key: :second_driver_id

  ################################ Valadations ########################
	validates :name, presence: true
	validates :color, presence: true
	validates :modle, presence: true
	validates :vehicle_number, presence: true
	validates :avatar, attached: true, content_type: [:png, :jpg, :jpeg]

end

app/models/vehicle_material.rb
class VehicleMaterial < ApplicationRecord
	################################ Relationships ########################
	belongs_to :meterail
	belongs_to :Vehicle

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plant, only: %i[ show edit update destroy ]

  
  def index
    @plants = Plant.all
  end

  def show
  end

  def new
    @plant = Plant.new
  end

  def edit
  end

  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_plant
      @plant = Plant.find(params[:id])
    end

    def plant_params
      params.require(:plant).permit(:name, :address, :avatar)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all.order(:id)

  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
    @rooms = Room.all
    render 'index'

  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end
  def room_params
		params.require(:room).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/fields/gravatar_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.text_field field.attribute %>
</div>

app/views/fields/gravatar_field/_index.html.erb
<%= field.to_s %>

app/views/fields/gravatar_field/_show.html.erb
<%= field.to_s %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<div class= "footer pt-4 h-104 fixed-bottom">
      <ul class="list-inline">
            © 2020 Copyright: <a class="text-light">transproters</a>
          <li class="list-inline-item position-absolute bottom-2 end-0">
            <a href="https://github.com/sahilkhan1432k" role="button"><i class="bi-github text-end"></i></a>
            <a href="https://web.facebook.com/sahil143n"><i class="bi bi-facebook"></i></a>
            <a href="https://www.instagram.com/sahilkhan1432k2020/"><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-twitter"></i></a>
            <%= link_to 'About Us ', home_about_path , class:'text-gray-400 p-3' %>
          </li>
      </ul>
</div>

app/views/layouts/_form.html.erb
<form name="my-form" onsubmit="return validform()" action="success.php" method="">
  <div class="form-group row">
      <label for="full_name" class="col-md-4 col-form-label text-md-right">First Name</label>
      <div class="col-md-6">
        <%= text_field :first_name, autofocus: true %>
      </div>
  </div>
  <div class="form-group row">
      <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>
      <div class="col-md-6">
        <%= text_field :last_name, autofocus: true %>
      </div>
  </div>

  <div class="form-group row">
      <label for="licence_number" class="col-md-4 col-form-label text-md-right"> Licence Number</label>
      <div class="col-md-6">
        <%= text_field :licence_number, autofocus: true %>
      </div>
  </div>

  <div class="form-group row">
      <label for="birthday" class="col-md-4 col-form-label text-md-right">birthday</label>
      <div class="col-md-6">
        <%= text_field :birthday, autofocus: true, autocomplete: "date" %>
      </div>
  </div>

  <div class="form-group row">
      <label for="address" class="col-md-4 col-form-label text-md-right">Address</label>
      <div class="col-md-6">
        <%= text_field :address, autofocus: true, autocomplete: "string" %>
      </div>
  </div>

  <div class="form-group row">
      <label for="user_type" class="col-md-4 col-form-label text-md-right">User type</label>
      <div class="col-md-6">
        <%= text_field :user_type, autofocus: true, autocomplete: "string" %>
      </div>
  </div>

  <div class="form-group row">
      <label for="email" class="col-md-4 col-form-label text-md-right">Email </label>
      <div class="col-md-6">
        <%= email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
  </div>

  <div class="form-group row">
      <label for="password" class="col-md-4 col-form-label text-md-right">password</label>
      <div class="col-md-6">
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= password_field :password, autocomplete: "new-password" %>
      </div>
  </div>
  <div class="form-group row">
    <label for="password_confirmation" class="col-md-4 col-form-label text-md-right">Confirm password </label>
    <div class="col-md-6">
      <%= password_field :password_confirmation, autocomplete: "new-password" %>
    </div>
  </div>
  
    
</form>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div id="user-id" data-user-id="<%= current_user&.id %>"></div>
  <div class="container-fluid">
    <button class="navbar-toggler text-end" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon toggler"><i class="bi bi-border-width"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll justify-content-center" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
         <a href="/" class="nav-link">
            <i class=" active bi bi-house fw-bold"  > Home</i>
          </a>
        </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Vehicles', vehicles_path ,class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Plants', plants_path ,class: 'nav-link'  %>
            </li>

          <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path ,class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path ,class: 'nav-link' %>
          </li>
          <% end %>
      </ul>
    </div>
    <div class="d-flex align-items-center">
      <% if user_signed_in? %>

        <div   id="navbarScrollingDropdown"  data-bs-toggle="dropdown" aria-expanded="false">
          <%if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class: 'rounded-circle shard_link nav-link dropdown-toggle d-flex align-items-center hidden-arrow btn  '  %>
        <% else %>
        <% end %>
        </div>
        <ul class="dropdown-menu dropdown-menu-end"ria-labelledby="navbarDropdownMenuLink">
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete ,class: 'dropdown-item'  %></li>
          <% if current_user.admin? %>
           <li><%= link_to "Admin Area", admin_root_path, class: 'dropdown-item' %></li>
         <% end %>
          <li><%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
          <li><%= link_to 'My Vehicles', my_vehicles_vehicles_path, class: 'dropdown-item' %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <meta charset = "utf-8" />

        <title>
            Transproters
        </title>

        <!-- add icon link -->
        <link rel = "icon" src =
        "assets/images/Title.png"
        type = "image/x-icon">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body class= "bg-light">
  <%= render 'layouts/navbar' %>
  <div class="container">
      <%if notice%>
      <%= render 'layouts/alerts'%>
      <% end %>
    <p class="alert alert text-center"><%= alert %></p>
    <%= yield %>
  </body><br><br><br><br>
  <footer>
    <%= render 'layouts/footer'%>
  </footer>
</html>